### ISSUE TITLE
字体引用问题

### ISSUE THREAD

**Issue by unclecode1024** [adozhao/halo-theme-zero#2]
国内无法访问gstatic，希望能换成其他源或者可以自定义
![image](https://github.com/adozhao/halo-theme-zero/assets/113070257/213b2bd5-20f9-4c80-815b-e44a12709dc7)

**Comment by adozhao** [comment]
一直挂着代理，所以没太注意这个问题，感谢反馈~  

目前问题已处理，处理方案如下：  
- 由于版权和性能问题，咱们不额外引入字体，已删除多余的字体引用
- 修改后的引用的所有字体均为操作系统（win10）或浏览器（chrome / edge）自带
- 修改后的版面整体效果不错，有过之而无不及（个人认为）

**Comment by adozhao** [comment]
halo版本已更新~
