### ISSUE TITLE
如何将评论的回复展开

### ISSUE THREAD

**Issue by yulongsa** [adozhao/halo-theme-zero#3]
因为站点访问用户不多，评论也不多。
所以觉得将评论的回复折叠没有什么效果。具体可以改动哪里不折叠评论呢

**Comment by adozhao** [comment]
以下是halo官方对于此问题的解决进度，可以关注下~   

[#5435](https://github.com/halo-dev/halo/issues/5435)

**Comment by adozhao** [comment]
已确认，halo将于2.14.0版本新增此特性，支持评论回复展开～ @yulongsa

**Comment by yulongsa** [comment]
> 已确认，halo将于2.14.0版本新增此特性，支持评论回复展开～ @yulongsa

非常感谢
